### ISSUE TITLE
Support IDEA 2016.1

### ISSUE THREAD

**Issue by strubell** [sylvanaar/IDLua#5]
I just upgraded to:
IntelliJ IDEA 2016.1
Build #IU-145.258, built on March 17, 2016

and I get the following error:
```
Unknown Module Type
           Cannot determine module type ("LUA_MODULE") for the following module:"nn-depparse"
           The module will be treated as a Unknown module.
```
and no Lua support. 

Please update to support the newest build of IDEA :)

**Comment by sylvanaar** [comment]
I have posted a new build, please try and update the plugin using the plugin manager.
